# Generated by Django 3.1.3 on 2020-11-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=320, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Nome utente')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Data di registrazione')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Ultimo login')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Amministratore')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superutente')),
                ('first_name', models.CharField(max_length=255, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=255, verbose_name='Cognome')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Numero di telefono')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data di nascita')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
