# Generated by Django 3.1.3 on 2020-11-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Utente', 'verbose_name_plural': 'Utenti'},
        ),
    ]
